ALTER TABLE INSTITUTIONS ADD VIRTUAL NUMBER(1, 0) DEFAULT 0 NOT NULL;

INSERT INTO INSTITUTIONS (PIC, ERASMUS_CODE, NAME, NAME_EN, COUNTRY_CODE, IDP_ENTITY_ID, IDP_METADATA_URL, DISPLAY_NAME, VIRTUAL)
  SELECT
    NULL,
    NULL,
    NAME,
    NULL,
    CODE,
    NULL,
    NULL,
    NAME,
    1
  FROM COUNTRIES;