-- Remove data sheet rows that should be linked to an institution but aren't because of EQUAT-130
ALTER TABLE DATA_SHEET_ROW_VALUES DROP CONSTRAINT DATA_SHEET_ROW_VALUES_ROWS_FK;
ALTER TABLE DATA_SHEET_ROW_VALUES ADD CONSTRAINT DATA_SHEET_ROW_VALUES_ROWS_FK FOREIGN KEY (ROW_ID) REFERENCES DATA_SHEET_ROWS (ID) ON DELETE CASCADE;

DELETE FROM DATA_SHEET_ROWS WHERE DATA_SHEET_CODE in ('SMS', 'SMP') AND INST_ID IS NULL;