INSERT INTO DATA_SHEETS (CODE) VALUES ('STUDENTS_INCOMING');

INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE)
VALUES ('DATE', 'DATE', 0, 0);
INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE)
VALUES ('CREDITS', 'INTEGER', 0, 0);

INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('START_DATE');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('END_DATE');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('CREDITS_TAKEN');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('CREDITS_COMPLETED');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'STUDENTS_INCOMING', 'PIC', 'Sending Organisation PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'STUDENTS_INCOMING', 'ERASMUS_CODE', 'Sending Organisation Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'STUDENTS_INCOMING', 'LEGAL_NAME', 'Sending Organisation Legal Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'STUDENTS_INCOMING', 'COUNTRY_CODE', 'Sending Organisation Country');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ISCED_CODE', 'STUDENTS_INCOMING', 'ISCED_CODE', 'Field of Education');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('START_DATE', 'STUDENTS_INCOMING', 'DATE', 'Start Date');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('END_DATE', 'STUDENTS_INCOMING', 'DATE', 'End date');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('CREDITS_TAKEN', 'STUDENTS_INCOMING', 'CREDITS', 'Credits taken');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('CREDITS_COMPLETED', 'STUDENTS_INCOMING', 'CREDITS', 'Credits successfully completed');

ALTER TABLE DATA_SHEET_ROW_VALUES ADD DATE_VALUE DATE;