INSERT INTO DATA_SHEETS (CODE) VALUES ('STAFF_INCOMING');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'STAFF_INCOMING', 'PIC', 'Sending Organisation PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'STAFF_INCOMING', 'ERASMUS_CODE', 'Sending Organisation Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'STAFF_INCOMING', 'LEGAL_NAME', 'Sending Organisation Legal Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'STAFF_INCOMING', 'COUNTRY_CODE', 'Sending Organisation Country');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ISCED_CODE', 'STAFF_INCOMING', 'ISCED_CODE', 'Field of Education');