INSERT INTO DATA_SHEETS (CODE) VALUES ('STAFF_OUTGOING');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'STAFF_OUTGOING', 'PIC', 'Receiving Organisation PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'STAFF_OUTGOING', 'ERASMUS_CODE', 'Receiving Organisation Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'STAFF_OUTGOING', 'LEGAL_NAME', 'Receiving Organisation Legal Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'STAFF_OUTGOING', 'COUNTRY_CODE', 'Receiving Organisation Country');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ISCED_CODE', 'STAFF_OUTGOING', 'ISCED_CODE', 'Field of Education');