INSERT INTO DATA_SHEETS (CODE) VALUES ('PARTNER_INSTITUTIONS');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'PARTNER_INSTITUTIONS', 'PIC', 'Partner Institution PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'PARTNER_INSTITUTIONS', 'ERASMUS_CODE', 'Partner Institution Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'PARTNER_INSTITUTIONS', 'LEGAL_NAME', 'Partner Institution Legal Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'PARTNER_INSTITUTIONS', 'COUNTRY_CODE', 'Partner Institution Country');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ISCED_CODE', 'PARTNER_INSTITUTIONS', 'ISCED_CODE', 'Field of Education');