ALTER TABLE COUNTRIES ADD ALTERNATIVE_CODE VARCHAR2(2);
ALTER TABLE COUNTRIES ADD CONSTRAINT COUNTRIES_ALTER_CODE_UK UNIQUE (ALTERNATIVE_CODE);

UPDATE COUNTRIES SET ALTERNATIVE_CODE = 'UK' WHERE CODE = 'GB';
UPDATE COUNTRIES SET ALTERNATIVE_CODE = 'EL' WHERE CODE = 'GR';