DELETE FROM DATA_SHEET_ROW_VALUES WHERE COLUMN_CODE = 'SMS_OBSTACLES';
DELETE FROM DATA_SHEET_ROW_VALUES WHERE COLUMN_CODE = 'SMP_OBSTACLES';

DELETE FROM DATA_SHEET_UPLOAD_ERRORS WHERE COLUMN_ID IN (
  SELECT ID FROM DATA_SHEET_COLUMNS WHERE CODE = 'SMS_OBSTACLES'
);
DELETE FROM DATA_SHEET_UPLOAD_ERRORS WHERE COLUMN_ID IN (
  SELECT ID FROM DATA_SHEET_COLUMNS WHERE CODE = 'SMP_OBSTACLES'
);

DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_TRANSCRIPT';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_TAKE';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_PASS';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_CONTENT';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_RECOGNISED';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_TRANSFER';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_PROFESSOR';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_NOT';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMS_OTHER';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMP_CERTIFICATE';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMP_CONTENT';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMP_CALCULATION';
DELETE FROM DATA_SHEET_VALUES WHERE CODE = 'OBSTACLES_SMP_OTHER';

DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_TRANSCRIPT';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_TAKE';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_PASS';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_CONTENT';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_RECOGNISED';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_TRANSFER';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_PROFESSOR';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_NOT';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMS_OTHER';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMP_CERTIFICATE';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMP_CONTENT';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMP_CALCULATION';
DELETE FROM DATA_SHEET_VALUE_CODES WHERE CODE = 'OBSTACLES_SMP_OTHER';

DELETE FROM DATA_SHEET_COLUMNS WHERE CODE = 'SMS_OBSTACLES';
DELETE FROM DATA_SHEET_COLUMNS WHERE CODE = 'SMP_OBSTACLES';

DELETE FROM DATA_SHEET_COLUMN_CODES WHERE CODE = 'SMS_OBSTACLES';
DELETE FROM DATA_SHEET_COLUMN_CODES WHERE CODE = 'SMP_OBSTACLES';

DELETE FROM DATA_SHEET_COLUMN_TYPES WHERE CODE = 'OBSTACLES_SMS';
DELETE FROM DATA_SHEET_COLUMN_TYPES WHERE CODE = 'OBSTACLES_SMP';