INSERT INTO DATA_SHEETS (CODE) VALUES ('STUDENTS_OUTGOING');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'STUDENTS_OUTGOING', 'PIC', 'Receiving Organisation PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'STUDENTS_OUTGOING', 'ERASMUS_CODE', 'Receiving Organisation Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'STUDENTS_OUTGOING', 'LEGAL_NAME', 'Receiving Organisation Legal Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'STUDENTS_OUTGOING', 'COUNTRY_CODE', 'Receiving Organisation Country');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ISCED_CODE', 'STUDENTS_OUTGOING', 'ISCED_CODE', 'Field of Education');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('START_DATE', 'STUDENTS_OUTGOING', 'DATE', 'Start Date');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('END_DATE', 'STUDENTS_OUTGOING', 'DATE', 'End date');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('CREDITS_TAKEN', 'STUDENTS_OUTGOING', 'CREDITS', 'Credits taken');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('CREDITS_COMPLETED', 'STUDENTS_OUTGOING', 'CREDITS', 'Credits successfully completed');