UPDATE DATA_SHEET_VALUE_CODES SET DEFAULT_VALUE = 2 WHERE CODE = 'COURSE_CATALOGUE_COMPLETE';
UPDATE DATA_SHEET_VALUE_CODES SET DEFAULT_VALUE = 3 WHERE CODE = 'COURSE_CATALOGUE_IN_TIME';
UPDATE DATA_SHEET_VALUE_CODES SET DEFAULT_VALUE = 4 WHERE CODE = 'COURSE_CATALOGUE_UP_TO_DATE';