INSERT INTO DATA_SHEETS (CODE) VALUES ('GRADING_TABLES');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'GRADING_TABLES', 'PIC', 'Partner Institution PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'GRADING_TABLES', 'ERASMUS_CODE', 'Partner Institution Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'GRADING_TABLES', 'LEGAL_NAME', 'Partner Institution Legal Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'GRADING_TABLES', 'COUNTRY_CODE', 'Partner Institution Country');