ALTER TABLE DATA_SHEET_UPLOADS
  ADD INST_ID INTEGER CONSTRAINT DATA_SHEET_UPLOADS_INST_FK REFERENCES INSTITUTIONS (ID);

UPDATE DATA_SHEET_UPLOADS SET INST_ID = (SELECT INST_ID FROM USERS WHERE USERS.ID = DATA_SHEET_UPLOADS.USER_ID);