CREATE TABLE SCORE_INTERPRETATIONS
(
  ID INTEGER NOT NULL,
  INST_ID INTEGER NOT NULL,
  FAIR_SCORE_MIN NUMBER DEFAULT 50 NOT NULL,
  GOOD_SCORE_MIN NUMBER DEFAULT 65 NOT NULL,
  CONSTRAINT SCORE_INTERP_PK PRIMARY KEY (ID),
  CONSTRAINT SCORE_INTERP_INST_FK FOREIGN KEY (INST_ID) REFERENCES INSTITUTIONS (ID),
  CONSTRAINT SCORE_INTERP_INST_UK UNIQUE (INST_ID)
);

CREATE SEQUENCE SCORE_INTERP_SEQ;
CREATE OR REPLACE TRIGGER T_SCORE_INTERP_SEQ
BEFORE INSERT ON SCORE_INTERPRETATIONS
FOR EACH ROW
WHEN (new.id is null)
  BEGIN
    SELECT SCORE_INTERP_SEQ.NEXTVAL
    INTO   :new.id
    FROM   dual;
  END;
/
ALTER TRIGGER T_SCORE_INTERP_SEQ ENABLE;