INSERT INTO DATA_SHEET_VALUE_CODES (CODE) VALUES ('COURSE_CATALOGUE_ECTS_BASED');
INSERT INTO DATA_SHEET_VALUE_CODES (CODE) VALUES ('COURSE_CATALOGUE_LANGUAGE');

INSERT INTO DATA_SHEET_VALUES (CODE, COLUMN_TYPE, VALUE)
VALUES ('COURSE_CATALOGUE_ECTS_BASED', 'COURSE_CATALOGUE', 'ECTS-based?');
INSERT INTO DATA_SHEET_VALUES (CODE, COLUMN_TYPE, VALUE)
VALUES ('COURSE_CATALOGUE_LANGUAGE', 'COURSE_CATALOGUE', 'Available in a widely spoken international language?');