UPDATE DATA_SHEET_COLUMNS
SET TYPE = 'NAME'
WHERE TYPE = 'LEGAL_NAME';
UPDATE DATA_SHEET_COLUMNS
SET TYPE = 'NAME'
WHERE TYPE = 'NAME_EN';

DELETE FROM DATA_SHEET_COLUMN_TYPES
WHERE CODE = 'LEGAL_NAME';
DELETE FROM DATA_SHEET_COLUMN_TYPES
WHERE CODE = 'NAME_EN';