INSERT INTO DATA_SHEETS (CODE) VALUES ('EDUCATIONAL_PROJECTS');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'EDUCATIONAL_PROJECTS', 'PIC', 'Partner Institution PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'EDUCATIONAL_PROJECTS', 'ERASMUS_CODE', 'Partner Institution Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'EDUCATIONAL_PROJECTS', 'NAME', 'Partner Institution Legal Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'EDUCATIONAL_PROJECTS', 'COUNTRY_CODE', 'Partner Institution Country');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('URL', 'EDUCATIONAL_PROJECTS', 'URL', 'Partner institution URL');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ISCED_CODE', 'EDUCATIONAL_PROJECTS', 'ISCED_CODE', 'Field of education');