INSERT INTO DATA_SHEETS (CODE) VALUES ('JOINT_PROGRAMMES');

INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE) VALUES ('NUMBER', 'NUMERIC');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('GRADUATES_NUMBER');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'JOINT_PROGRAMMES', 'PIC', 'Partner Institution PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'JOINT_PROGRAMMES', 'ERASMUS_CODE', 'Partner Institution Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'JOINT_PROGRAMMES', 'NAME', 'Partner Institution Legal Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'JOINT_PROGRAMMES', 'COUNTRY_CODE', 'Partner Institution Country');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('URL', 'JOINT_PROGRAMMES', 'URL', 'Partner institution URL');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ISCED_CODE', 'JOINT_PROGRAMMES', 'ISCED_CODE', 'Field of education');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('GRADUATES_NUMBER', 'JOINT_PROGRAMMES', 'NUMBER', 'Joint programme number of graduates');