INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('PROJECT_NAME');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PROJECT_NAME', 'EDUCATIONAL_PROJECTS', 'NAME', 'Project name');