INSERT INTO DATA_SHEETS (CODE) VALUES ('INSTITUTIONS');

INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE) VALUES ('PIC', 'STRING', 0, 0);
INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE) VALUES ('ERASMUS_CODE', 'STRING', 0, 0);
INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE) VALUES ('NAME', 'STRING', 0, 0);
INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE) VALUES ('NAME_EN', 'STRING', 0, 0);
INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE) VALUES ('COUNTRY_CODE', 'STRING', 0, 0);

INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('PIC');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('ERASMUS_CODE');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('NAME');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('NAME_EN');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('COUNTRY_CODE');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE) VALUES ('PIC', 'INSTITUTIONS', 'PIC', 'PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE) VALUES ('ERASMUS_CODE', 'INSTITUTIONS', 'ERASMUS_CODE', 'ERASMUS_CODE');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE) VALUES ('NAME', 'INSTITUTIONS', 'NAME', 'NAME');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE) VALUES ('NAME_EN', 'INSTITUTIONS', 'NAME_EN', 'NAME_EN');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE) VALUES ('COUNTRY_CODE', 'INSTITUTIONS', 'COUNTRY_CODE', 'COUNTRY_CODE');