INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_FACILITIES_ACCESS_INTERNET', 'SMS', 'PFG', 'Access to Internet');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_FACILITIES_CLASSROOM', 'SMS', 'PFG', 'Classrooms');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_SUPPORT_INITIATIVES', 'SMS', 'SATISFIED', 'Support from student initiatives/organisations');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_SUPPORT_MENTORING', 'SMS', 'SATISFIED', 'Academic mentoring');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_SUPPORT_ADMINISTRATIVE', 'SMS', 'SATISFIED', 'Administrative support arrangement');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_QUALITY_TEACHING', 'SMS', 'SATISFIED', 'The quality of teaching methods');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_QUALITY_CONTENT', 'SMS', 'SATISFIED', 'The quality of content of courses');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_QUALITY_LEARNING', 'SMS', 'SATISFIED', 'The degree of learning support received');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_FACILITIES_ACCESS_PUBLICATIONS', 'SMS', 'PFG', 'Access to existing research (publications)');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_FACILITIES_CAFETERIA', 'SMS', 'PFG', 'Cafeteria / canteen');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_FACILITIES_ACCESS_PC', 'SMS', 'PFG', 'Access to PCs');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_FACILITIES_LIBRARIES', 'SMS', 'PFG', 'Libraries');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('SMS_FACILITIES_STUDY_ROOMS', 'SMS', 'PFG', 'Study rooms, labs or similar');