CREATE INDEX DATA_SHEET_COLUMNS_CODE_FDX ON DATA_SHEET_COLUMNS(DATA_SHEET_CODE);
CREATE INDEX DATA_SHEET_COLUMNS_CODES_FDX ON DATA_SHEET_COLUMNS(CODE);

CREATE INDEX DATA_SHEET_ROWS_YEARS_FDX ON DATA_SHEET_ROWS(ACADEMIC_YEAR);
CREATE INDEX DATA_SHEET_ROWS_PART_INST_FDX ON DATA_SHEET_ROWS(PARTNER_INST_ID);
CREATE INDEX DATA_SHEET_ROWS_INST_FDX ON DATA_SHEET_ROWS(INST_ID);
CREATE INDEX DATA_SHEET_ROWS_ISCED_FDX ON DATA_SHEET_ROWS(ISCED_CODE);
CREATE INDEX DATA_SHEET_ROWS_CODE_FDX ON DATA_SHEET_ROWS(DATA_SHEET_CODE);

CREATE INDEX DATA_SHEET_ROW_VAL_VAL_COD_FDX ON DATA_SHEET_ROW_VALUES(VALUE_CODE);
CREATE INDEX DATA_SHEET_ROW_VAL_COL_COD_FDX ON DATA_SHEET_ROW_VALUES(COLUMN_CODE);
CREATE INDEX DATA_SHEET_ROW_VALUES_ROWS_FDX ON DATA_SHEET_ROW_VALUES(ROW_ID);

CREATE INDEX DATA_SHEET_UPLOAD_ERR_UPL_FDX ON DATA_SHEET_UPLOAD_ERRORS(UPLOAD_ID);

CREATE INDEX DATA_SHEET_UPLOADS_INST_FDX ON DATA_SHEET_UPLOADS(INST_ID);

CREATE INDEX DATA_SHEET_VALUES_CODES_FDX ON DATA_SHEET_VALUES(CODE);

CREATE INDEX INSTITUTION_COUNTRY_FDX ON INSTITUTIONS(COUNTRY_CODE);

CREATE INDEX USERS_INST_FDX ON USERS(INST_ID);