INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0100','Education');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0110','Education, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0111','Education science');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0112','Training for pre-school teachers');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0113','Teacher training without subject specialisation');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0114','Teacher training with subject specialization');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0119','Education, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0188','Education, inter-disciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0200','Arts and humanities');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0210','Arts, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0211','Audio-visual techniques and media production');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0212','Fashion, interior and industrial design');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0213','Fine arts ');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0214','Handicrafts');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0215','Music and performing arts');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0219','Arts, not elsewhere classified ');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0220','Humanities (except languages), not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0221','Religion and theology');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0222','History and archaeology');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0223','Philosophy and ethics');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0229','Humanities (except languages), not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0230','Language');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0231','Language acquisition');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0232','Literature and linguistics');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0239','Languages, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0288','Arts and humanities, interdisciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0300','Social sciences, journalism and information');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0310','Social and behavioural sciences, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0311','Economics');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0312','Political sciences and civics');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0313','Psychology');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0314','Sociology and cultural studies');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0319','Social and behavioural sciences, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0320','Journalism and information, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0321','Journalism and reporting');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0322','Library, information and archival studies');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0329','Journalism and information, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0388','Social sciences, journalism and information, inter-disciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0400','Business and administration and law');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0410','Business and administration, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0411','Accounting and taxation');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0412','Finance, banking and insurance');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0413','Management and administration');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0414','Marketing and advertising');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0415','Secretarial and office work');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0416','Wholesale and retail sales');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0417','Work skills');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0419','Business and administration, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0420','Law');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0421','Law');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0429','Law, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0488','Business, administration and law, interdisciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0500','Natural sciences, mathematics and statistics');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0510','Biological and related sciences');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0511','Biology');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0512','Biochemistry');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0519','Biological and related sciences, not elsewhere classifed');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0520','Environment');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0521','Environmental sciences');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0522','Natural environments and wildlife');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0529','Environment, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0530','Physical sciences');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0531','Chemistry');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0532','Earth science');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0533','Physics');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0539','Physical sciences, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0540','Mathematics and statistics, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0541','Mathematics');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0542','Statistics');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0549','Mathematics and statistics, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0588','Natural sciences, mathematics and statistics, inter-disciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0600','Information and Communication Technologies (ICTs)');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0610','Information and Communication Technologies (ICTs)');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0611','Computer use');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0612','Database and network design and administration');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0613','Software and applications development and analysis');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0619','Information and Communication Technologies (ICTs), not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0688','Information and Communication Technologies (ICTs), inter-disciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0700','Engineering, manufacturing and construction');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0710','Engineering and engineering trades, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0711','Chemical engineering and processes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0712','Environmental protection technology');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0713','Electricity and energy');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0714','Electronics and automation');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0715','Mechanics and metal trades');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0716','Motor vehicles, ships and aircraft');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0719','Engineering and engineering trades, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0720','Manufacturing and processing, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0721','Food processing');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0722','Materials (glass, paper, plastic and wood)');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0723','Textiles (clothes, footwear and leather)');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0724','Mining and extraction');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0729','Manufacturing and processing, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0730','Architecture and construction, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0731','Architecture and town planning');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0732','Building and civil engineering');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0739','Architecture and construction, not elsewhere classified ');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0788','Engineering, manufacturing and construction, inter-disciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0800','Agriculture, forestry, fisheries and veterinary');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0810','Agriculture, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0811','Crop and livestock production');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0812','Horticulture');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0819','Agriculture, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0820','Forestry');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0821','Forestry');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0829','Forestry, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0830','Fisheries');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0831','Fisheries');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0839','Fisheries, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0840','Veterinary');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0841','Veterinary');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0849','Veterinary, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0888','Agriculture, forestry, fisheries, veterinary, inter-disciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0900','Health and welfare');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0910','Health, not further defined');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0911','Dental studies');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0912','Medicine');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0913','Nursing and midwifery');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0914','Medical diagnostic and treatment technology');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0915','Therapy and rehabilitation');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0916','Pharmacy');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0917','Traditional and complementary medicine and therapy');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0919','Health, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0920','Welfare');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0921','Care of the elderly and of disabled adults');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0922','Child care and youth services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0923','Social work and counselling');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0929','Welfare, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('0988','Health and Welfare, inter-disciplinary programmes');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1000','Services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1010','Personal services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1011','Domestic services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1012','Hair and beauty services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1013','Hotel, restaurants and catering');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1014','Sports');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1015','Travel, tourism and leisure');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1019','Personal services, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1020','Hygiene and occupational health services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1021','Community sanitation');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1022','Occupational health and safety');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1029','Hygiene and occupational health services, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1030','Security services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1031','Military and defence');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1032','Protection of persons and property');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1039','Security services, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1040','Transport services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1041','Transport services');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1049','Transport services, not elsewhere classified');
INSERT INTO ISCEDS (CODE, FIELD_NAME) VALUES ('1088','Services, inter-disciplinary programmes');

INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE) VALUES ('ISCED_CODE', 'STRING', 0, 0);

INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('ISCED_CODE');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE) VALUES ('ISCED_CODE','SMS','ISCED_CODE','Field of Education');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE) VALUES ('ISCED_CODE','SMP','ISCED_CODE','Field of Education');