INSERT INTO DATA_SHEETS (CODE) VALUES ('RANKINGS');

INSERT INTO DATA_SHEET_COLUMN_TYPES (CODE, VALUE_TYPE, IS_FIXED_VALUE, IS_MULTIPLE_CHOICE)
VALUES ('POSITION', 'STRING', 0, 0);

INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('RANKING_AWRU_POSITION');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('RANKING_THE_POSITION');
INSERT INTO DATA_SHEET_COLUMN_CODES (CODE) VALUES ('RANKING_QS_POSITION');

INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('PIC', 'RANKINGS', 'PIC', 'Institution PIC');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('ERASMUS_CODE', 'RANKINGS', 'ERASMUS_CODE', 'Institution Erasmus Code');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('LEGAL_NAME', 'RANKINGS', 'LEGAL_NAME', 'Institution Name');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('COUNTRY_CODE', 'RANKINGS', 'COUNTRY_CODE', 'Country');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('RANKING_AWRU_POSITION', 'RANKINGS', 'POSITION', 'ARWU');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('RANKING_THE_POSITION', 'RANKINGS', 'POSITION', 'THE');
INSERT INTO DATA_SHEET_COLUMNS (CODE, DATA_SHEET_CODE, TYPE, TITLE)
VALUES ('RANKING_QS_POSITION', 'RANKINGS', 'POSITION', 'QS');

ALTER TABLE DATA_SHEET_ROWS MODIFY INST_ID NULL;

ALTER TABLE DATA_SHEET_ROW_VALUES ADD VALUE VARCHAR2(200) NULL;