package be.ugent.equatic.domain;

public enum DataSheetCode {
    INSTITUTIONS,
    SMS,
    SMP,
    RANKINGS,
    STUDENTS_INCOMING,
    STUDENTS_OUTGOING,
    STAFF_INCOMING,
    STAFF_OUTGOING,
    INSTITUTIONAL_AGREEMENTS,
    GRADING_TABLES,
    EDUCATIONAL_PROJECTS,
    JOINT_PROGRAMMES
}
